# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gewaspercelen2016',
            fields=[
                ('objectid', models.DecimalField(decimal_places=65535, max_digits=65535, unique=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('cat_gewasc', models.CharField(blank=True, max_length=60, null=True)),
                ('gws_gewasc', models.CharField(blank=True, max_length=10, null=True)),
                ('geometrie_field', models.DecimalField(blank=True, db_column='geometrie_', decimal_places=65535, max_digits=65535, null=True)),
                ('geometri_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('gws_gewas', models.CharField(blank=True, max_length=254, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gewaspercelen2016',
                'managed': False,
            },
        ),
    ]
